### ISSUE TITLE
Standard Libary

### ISSUE THREAD

**Issue by armudgal** [Yashvardhan-Kukreja/CryptoLert#1]
Hey,
Loved the repo, I would suggest to transform the code to use stdlib so that anyone can fork this and are ready to go.

**Comment by yashvardhan-kukreja** [comment]
Shifted the code to use urllib.request to make API Calls. Regarding the sound alert, it's necessary to use pygame to play the sound because if I use "wave" standard library, then the program will only be able to read the sound file but not play it. I could have used "winsound" library but it works only on windows. So, pygame seemed the best library to play the sound file.
